apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    chart: frontend
spec:
  selector:
    matchLabels:
      app: "frontend-selector"
  template:
    metadata:
      labels:
        app: "frontend-selector"
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        livenessProbe:
          httpGet: 
            path: /
            port: {{ .Values.frontend.servicePort}}
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: {{ .Values.frontend.servicePort}}
        env:
          - name: SERVICE_URL
            value: "backend.default.svc.cluster.local:{{ .Values.backend.servicePort}}"
