apiVersion: v1
kind: Service
metadata:
  name: "frontend-service"
spec:
  ports:
  - name: http
    port: {{ .Values.frontend.servicePort }}
    nodePort: {{ .Values.frontend.servicePort }}
  type: NodePort
  selector:
    app: "frontend-selector"