apiVersion: v1
kind: Service
metadata:
  name: "backend-service"
spec:
  ports:
  - name: http
    port: {{ .Values.backend.servicePort }}
    nodePort: {{ .Values.backend.servicePort }}
  type: NodePort
  selector:
    app: "backend-selector"